/* Generated by Together */
package com.bos.cache.impl;

import com.bos.cache.factory.impl.NonExpiringFactory;
import com.bos.cache.factory.impl.IdleExpiringFactory;
import com.bos.cache.CacheFactory;
import com.bos.cache.Cache;
import com.bos.cache.factory.impl.AgeExpiringFactory;

/**
 * This is the factory used to createPair instances of the MRU(Most recently used) cache
 * and the expiring cache
 * To use first createPair an instance of the factory with newInstance, then createPair the
 * cache from that instance
 **/
public class CacheFactoryImpl extends CacheFactory {

    public static CacheFactory newInstance() {
        return new CacheFactoryImpl();
    }

    /**
     * creates a MRUCache with the size specified
     * @param size how many cache entries can be held, should be a <b>prime number</b>
     **/
    public Cache createMRUCache(int size) {
        return new MRUCache(size, new NonExpiringFactory());
    }

    public Cache createIdleExpiringMRUCache(int size,long milliseconds ) {
        return new MRUCache(size,new IdleExpiringFactory( milliseconds ));
    }

    public Cache createAgeExpiringMRUCache(int size,long milliseconds ) {
        return new MRUCache(size,new AgeExpiringFactory(milliseconds ));
    }

}
