/* Generated by Together */
package com.bos.cache;

import java.util.Map;

/**
 * defines the interface, with basic functions for putting and getting
 * data in and out of the cache and sizing the cache
 **/
public interface Cache<K,V> extends Map<K,V> {

}
