/* Generated by Together */

package com.bos.cache.factory.impl;
import com.bos.cache.impl.CacheData;

/**
* Defines the interface to the factory class
* used to createPair factory instances and instances of the caching classes
**/
abstract public class CacheDataFactory<K,V> {

    CacheDataFactory() {}

    /**
     * Defines the abstract method used to create a data pair (key/value)
     * @param key
     * @param value
     * @return returns the CacheData key/value pair
     */
    abstract public CacheData<K,V> createPair(K key,V value);
    abstract public CacheData<K,V> createPair(K key,int hash);

}
