/* Generated by Together */

package com.bos.cache.factory;
import com.bos.cache.data.CacheData;

/**
* Defines the interface to the factory class
* used to createPair factory instances and instances of the caching classes
**/
abstract public class CacheDataFactory<K,V> {

    protected CacheDataFactory() {}

    abstract public CacheData<K,V> createPair(K key,V value);
}
